// Package golang implements the Go module cache artifact metadata generator.
// It produces ArtifactEntry items describing the 6 files needed in
// $GOMODCACHE/cache/download/<module>/@v/ for offline Go builds.
//
// This generator runs at INGESTION TIME on the ROUTER.
// It produces METADATA ONLY — fetchers generate real content on-demand.
package golang

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"
	"unicode"

	"github.com/radryc/monofs/internal/buildcache"
)

// Generator produces Go module download-cache metadata entries.
type Generator struct{}

// NewGenerator creates a new Go module cache artifact generator.
func NewGenerator() *Generator { return &Generator{} }

func (g *Generator) BuildSystem() string { return "go" }

func (g *Generator) ShouldGenerate(ingestionType string) bool {
	return ingestionType == "go"
}

// GenerateEntries produces 6 metadata entries for a Go module@version:
//   - list          — version list file
//   - v{ver}.info   — version metadata JSON
//   - v{ver}.mod    — go.mod content
//   - v{ver}.zip    — source archive
//   - v{ver}.ziphash — zip checksum (h1:...)
//   - v{ver}.lock   — empty download-complete sentinel
//
// These are METADATA ONLY — content is generated by fetchers on read.
func (g *Generator) GenerateEntries(params buildcache.ArtifactParams) ([]buildcache.ArtifactEntry, error) {
	if params.ModulePath == "" || params.Version == "" {
		return nil, fmt.Errorf("module_path and version are required for Go cache artifacts")
	}

	escapedPath := EscapeModulePath(params.ModulePath)
	cachePrefix := fmt.Sprintf("cache/download/%s/@v", escapedPath)

	commonMeta := map[string]string{
		"module":      params.ModulePath,
		"version":     params.Version,
		"generatable": "true",
	}

	// Pre-compute sizes where possible.
	// list: deterministic content = version + "\n"
	// lock: always empty
	// mod:  same as the ingested go.mod (passed via GoModFileSize)
	// info, zip, ziphash: depend on proxy/fetcher, size unknown at ingestion time
	listSize := uint64(len(params.Version) + 1) // "v1.6.0\n"

	entries := []buildcache.ArtifactEntry{
		{
			RelativePath: fmt.Sprintf("%s/%s.info", cachePrefix, params.Version),
			Type:         buildcache.ArtifactGoModInfo,
			Size:         0, // fetched from proxy on-demand
			Metadata:     withType(commonMeta, buildcache.ArtifactGoModInfo),
		},
		{
			RelativePath: fmt.Sprintf("%s/%s.mod", cachePrefix, params.Version),
			Type:         buildcache.ArtifactGoModFile,
			Size:         params.GoModFileSize, // from ingested go.mod
			Metadata:     withType(commonMeta, buildcache.ArtifactGoModFile),
		},
		{
			RelativePath: fmt.Sprintf("%s/%s.zip", cachePrefix, params.Version),
			Type:         buildcache.ArtifactGoModZip,
			Size:         0, // built on-demand by fetcher
			Metadata:     withType(commonMeta, buildcache.ArtifactGoModZip),
		},
		{
			RelativePath: fmt.Sprintf("%s/%s.ziphash", cachePrefix, params.Version),
			Type:         buildcache.ArtifactGoModZipHash,
			Size:         0, // depends on zip content
			Metadata:     withType(commonMeta, buildcache.ArtifactGoModZipHash),
		},
		{
			RelativePath: fmt.Sprintf("%s/list", cachePrefix),
			Type:         buildcache.ArtifactGoModList,
			Size:         listSize,
			Metadata:     withType(commonMeta, buildcache.ArtifactGoModList),
		},
		{
			RelativePath: fmt.Sprintf("%s/%s.lock", cachePrefix, params.Version),
			Type:         buildcache.ArtifactGoModLock,
			Size:         0, // empty sentinel
			Metadata:     withType(commonMeta, buildcache.ArtifactGoModLock),
		},
	}

	return entries, nil
}

// DeterministicHash generates a stable blob_hash for metadata-only entries.
// Used as the BlobHash for synthetic VirtualEntry items so the server can
// store and look them up. This is NOT the hash of file content.
func DeterministicHash(modulePath, version string, artifactType buildcache.ArtifactType) string {
	input := fmt.Sprintf("go-cache-artifact:%s@%s:%s", modulePath, version, artifactType)
	h := sha256.Sum256([]byte(input))
	return hex.EncodeToString(h[:])
}

// EscapeModulePath escapes uppercase letters as !lowercase per Go module proxy spec.
// e.g., "github.com/ProtonMail/go-crypto" → "github.com/!proton!mail/go-crypto"
func EscapeModulePath(path string) string {
	var b strings.Builder
	for _, r := range path {
		if unicode.IsUpper(r) {
			b.WriteRune('!')
			b.WriteRune(unicode.ToLower(r))
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// withType copies base metadata and adds artifact_type.
func withType(base map[string]string, t buildcache.ArtifactType) map[string]string {
	m := make(map[string]string, len(base)+1)
	for k, v := range base {
		m[k] = v
	}
	m["artifact_type"] = string(t)
	return m
}
