package migration

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// GenruleSpec describes a generated genrule that wraps a native build command.
type GenruleSpec struct {
	Name        string
	Command     string
	DisplayPath string
}

// GenerateFallbackGenrule produces a BUILD.bazel snippet with a genrule
// that wraps the native build system.
func GenerateFallbackGenrule(spec GenruleSpec) string {
	action := extractAction(spec.Command)
	return fmt.Sprintf(`# Generated by monofs-bazelctl -- native build fallback
# Repo: %s  State: native
# To migrate to Bazel:
#   monofs-bazelctl generate --repo=%s
#   monofs-bazelctl validate --repo=%s
#   monofs-bazelctl promote --repo=%s

genrule(
    name = %q,
    srcs = glob(["**/*"]),
    outs = [%q],
    cmd = "$(location //tools:monofs-native-build) %s %s $@",
    tools = ["//tools:monofs-native-build"],
    tags = ["native-build", "no-remote-exec"],
    visibility = ["//visibility:public"],
)
`, spec.DisplayPath, spec.DisplayPath, spec.DisplayPath, spec.DisplayPath,
		spec.Name, spec.Name+".done",
		spec.DisplayPath, action)
}

func extractAction(cmd string) string {
	parts := strings.Fields(cmd)
	if len(parts) >= 2 {
		return parts[1]
	}
	return cmd
}

// WriteFallbackGenrules writes BUILD.bazel files with genrule fallbacks
// for repos still in native/partial state.
func WriteFallbackGenrules(mountRoot string, repos []RepoStatus) ([]string, error) {
	var written []string

	for _, repo := range repos {
		if repo.State == StateActive || repo.State == StateHermetic {
			continue
		}

		repoDir := filepath.Join(mountRoot, repo.DisplayPath)
		cfg, err := LoadRepoConfig(repoDir)
		if err != nil {
			continue
		}

		// Generate both build and test genrules in a single BUILD.bazel.
		var content string
		content += GenerateFallbackGenrule(GenruleSpec{
			Name: "build", Command: cfg.FallbackBuild, DisplayPath: repo.DisplayPath,
		})
		content += "\n"
		content += GenerateFallbackGenrule(GenruleSpec{
			Name: "test", Command: cfg.FallbackTest, DisplayPath: repo.DisplayPath,
		})

		buildPath := filepath.Join(repoDir, "BUILD.bazel")

		if existing, err := os.ReadFile(buildPath); err == nil {
			if !strings.Contains(string(existing), "native build fallback") {
				continue
			}
		}

		if err := os.WriteFile(buildPath, []byte(content), 0644); err != nil {
			return written, fmt.Errorf("write fallback genrule for %s: %w", repo.DisplayPath, err)
		}
		written = append(written, filepath.Join(repo.DisplayPath, "BUILD.bazel"))
	}

	return written, nil
}

// RemoveFallbackGenrules removes BUILD.bazel files containing only fallback genrules.
func RemoveFallbackGenrules(mountRoot string, repos []RepoStatus) ([]string, error) {
	var removed []string

	for _, repo := range repos {
		buildPath := filepath.Join(mountRoot, repo.DisplayPath, "BUILD.bazel")
		data, err := os.ReadFile(buildPath)
		if err != nil {
			continue
		}
		if strings.Contains(string(data), "native build fallback") {
			if err := os.Remove(buildPath); err != nil {
				return removed, fmt.Errorf("remove fallback for %s: %w", repo.DisplayPath, err)
			}
			removed = append(removed, filepath.Join(repo.DisplayPath, "BUILD.bazel"))
		}
	}

	return removed, nil
}
