// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.31.1
// source: api/proto/fetcher.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlobFetcher_FetchBlob_FullMethodName      = "/monofs.BlobFetcher/FetchBlob"
	BlobFetcher_FetchBlobBatch_FullMethodName = "/monofs.BlobFetcher/FetchBlobBatch"
	BlobFetcher_PrefetchBlobs_FullMethodName  = "/monofs.BlobFetcher/PrefetchBlobs"
	BlobFetcher_CheckCache_FullMethodName     = "/monofs.BlobFetcher/CheckCache"
	BlobFetcher_GetStats_FullMethodName       = "/monofs.BlobFetcher/GetStats"
)

// BlobFetcherClient is the client API for BlobFetcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BlobFetcher service - stateless proxies for external data sources.
// Runs in DMZ with external network access. Storage nodes call this
// to fetch blobs without needing direct external connectivity.
type BlobFetcherClient interface {
	// Synchronous fetch - blocks until blob is returned or error.
	// Used for cache misses that need immediate data.
	FetchBlob(ctx context.Context, in *FetchBlobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error)
	// Batch fetch - parallel retrieval of multiple blobs.
	// Used for bulk prefetch operations.
	FetchBlobBatch(ctx context.Context, in *FetchBlobBatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchBlobBatchResponse], error)
	// Async prefetch - best-effort background fetch.
	// Returns immediately, blobs fetched in background.
	// Caller should poll or re-request via FetchBlob.
	PrefetchBlobs(ctx context.Context, in *PrefetchRequest, opts ...grpc.CallOption) (*PrefetchResponse, error)
	// Check if blobs are ready (cached on fetcher).
	CheckCache(ctx context.Context, in *CheckCacheRequest, opts ...grpc.CallOption) (*CheckCacheResponse, error)
	// Service health and statistics.
	GetStats(ctx context.Context, in *FetcherStatsRequest, opts ...grpc.CallOption) (*FetcherStatsResponse, error)
}

type blobFetcherClient struct {
	cc grpc.ClientConnInterface
}

func NewBlobFetcherClient(cc grpc.ClientConnInterface) BlobFetcherClient {
	return &blobFetcherClient{cc}
}

func (c *blobFetcherClient) FetchBlob(ctx context.Context, in *FetchBlobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BlobFetcher_ServiceDesc.Streams[0], BlobFetcher_FetchBlob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchBlobRequest, DataChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlobFetcher_FetchBlobClient = grpc.ServerStreamingClient[DataChunk]

func (c *blobFetcherClient) FetchBlobBatch(ctx context.Context, in *FetchBlobBatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchBlobBatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BlobFetcher_ServiceDesc.Streams[1], BlobFetcher_FetchBlobBatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchBlobBatchRequest, FetchBlobBatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlobFetcher_FetchBlobBatchClient = grpc.ServerStreamingClient[FetchBlobBatchResponse]

func (c *blobFetcherClient) PrefetchBlobs(ctx context.Context, in *PrefetchRequest, opts ...grpc.CallOption) (*PrefetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrefetchResponse)
	err := c.cc.Invoke(ctx, BlobFetcher_PrefetchBlobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobFetcherClient) CheckCache(ctx context.Context, in *CheckCacheRequest, opts ...grpc.CallOption) (*CheckCacheResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckCacheResponse)
	err := c.cc.Invoke(ctx, BlobFetcher_CheckCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobFetcherClient) GetStats(ctx context.Context, in *FetcherStatsRequest, opts ...grpc.CallOption) (*FetcherStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetcherStatsResponse)
	err := c.cc.Invoke(ctx, BlobFetcher_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlobFetcherServer is the server API for BlobFetcher service.
// All implementations must embed UnimplementedBlobFetcherServer
// for forward compatibility.
//
// BlobFetcher service - stateless proxies for external data sources.
// Runs in DMZ with external network access. Storage nodes call this
// to fetch blobs without needing direct external connectivity.
type BlobFetcherServer interface {
	// Synchronous fetch - blocks until blob is returned or error.
	// Used for cache misses that need immediate data.
	FetchBlob(*FetchBlobRequest, grpc.ServerStreamingServer[DataChunk]) error
	// Batch fetch - parallel retrieval of multiple blobs.
	// Used for bulk prefetch operations.
	FetchBlobBatch(*FetchBlobBatchRequest, grpc.ServerStreamingServer[FetchBlobBatchResponse]) error
	// Async prefetch - best-effort background fetch.
	// Returns immediately, blobs fetched in background.
	// Caller should poll or re-request via FetchBlob.
	PrefetchBlobs(context.Context, *PrefetchRequest) (*PrefetchResponse, error)
	// Check if blobs are ready (cached on fetcher).
	CheckCache(context.Context, *CheckCacheRequest) (*CheckCacheResponse, error)
	// Service health and statistics.
	GetStats(context.Context, *FetcherStatsRequest) (*FetcherStatsResponse, error)
	mustEmbedUnimplementedBlobFetcherServer()
}

// UnimplementedBlobFetcherServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlobFetcherServer struct{}

func (UnimplementedBlobFetcherServer) FetchBlob(*FetchBlobRequest, grpc.ServerStreamingServer[DataChunk]) error {
	return status.Error(codes.Unimplemented, "method FetchBlob not implemented")
}
func (UnimplementedBlobFetcherServer) FetchBlobBatch(*FetchBlobBatchRequest, grpc.ServerStreamingServer[FetchBlobBatchResponse]) error {
	return status.Error(codes.Unimplemented, "method FetchBlobBatch not implemented")
}
func (UnimplementedBlobFetcherServer) PrefetchBlobs(context.Context, *PrefetchRequest) (*PrefetchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrefetchBlobs not implemented")
}
func (UnimplementedBlobFetcherServer) CheckCache(context.Context, *CheckCacheRequest) (*CheckCacheResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckCache not implemented")
}
func (UnimplementedBlobFetcherServer) GetStats(context.Context, *FetcherStatsRequest) (*FetcherStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedBlobFetcherServer) mustEmbedUnimplementedBlobFetcherServer() {}
func (UnimplementedBlobFetcherServer) testEmbeddedByValue()                     {}

// UnsafeBlobFetcherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlobFetcherServer will
// result in compilation errors.
type UnsafeBlobFetcherServer interface {
	mustEmbedUnimplementedBlobFetcherServer()
}

func RegisterBlobFetcherServer(s grpc.ServiceRegistrar, srv BlobFetcherServer) {
	// If the following call panics, it indicates UnimplementedBlobFetcherServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlobFetcher_ServiceDesc, srv)
}

func _BlobFetcher_FetchBlob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchBlobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlobFetcherServer).FetchBlob(m, &grpc.GenericServerStream[FetchBlobRequest, DataChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlobFetcher_FetchBlobServer = grpc.ServerStreamingServer[DataChunk]

func _BlobFetcher_FetchBlobBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchBlobBatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlobFetcherServer).FetchBlobBatch(m, &grpc.GenericServerStream[FetchBlobBatchRequest, FetchBlobBatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlobFetcher_FetchBlobBatchServer = grpc.ServerStreamingServer[FetchBlobBatchResponse]

func _BlobFetcher_PrefetchBlobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrefetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobFetcherServer).PrefetchBlobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobFetcher_PrefetchBlobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobFetcherServer).PrefetchBlobs(ctx, req.(*PrefetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlobFetcher_CheckCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobFetcherServer).CheckCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobFetcher_CheckCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobFetcherServer).CheckCache(ctx, req.(*CheckCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlobFetcher_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetcherStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobFetcherServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobFetcher_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobFetcherServer).GetStats(ctx, req.(*FetcherStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlobFetcher_ServiceDesc is the grpc.ServiceDesc for BlobFetcher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlobFetcher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monofs.BlobFetcher",
	HandlerType: (*BlobFetcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrefetchBlobs",
			Handler:    _BlobFetcher_PrefetchBlobs_Handler,
		},
		{
			MethodName: "CheckCache",
			Handler:    _BlobFetcher_CheckCache_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _BlobFetcher_GetStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FetchBlob",
			Handler:       _BlobFetcher_FetchBlob_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FetchBlobBatch",
			Handler:       _BlobFetcher_FetchBlobBatch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/fetcher.proto",
}
