// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: api/proto/fetcher.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessType int32

const (
	AccessType_ACCESS_TYPE_UNKNOWN AccessType = 0
	AccessType_ACCESS_TYPE_READ    AccessType = 1 // File content read
	AccessType_ACCESS_TYPE_READDIR AccessType = 2 // Directory listing
	AccessType_ACCESS_TYPE_LOOKUP  AccessType = 3 // File/dir existence check
	AccessType_ACCESS_TYPE_GETATTR AccessType = 4 // Metadata retrieval
)

// Enum value maps for AccessType.
var (
	AccessType_name = map[int32]string{
		0: "ACCESS_TYPE_UNKNOWN",
		1: "ACCESS_TYPE_READ",
		2: "ACCESS_TYPE_READDIR",
		3: "ACCESS_TYPE_LOOKUP",
		4: "ACCESS_TYPE_GETATTR",
	}
	AccessType_value = map[string]int32{
		"ACCESS_TYPE_UNKNOWN": 0,
		"ACCESS_TYPE_READ":    1,
		"ACCESS_TYPE_READDIR": 2,
		"ACCESS_TYPE_LOOKUP":  3,
		"ACCESS_TYPE_GETATTR": 4,
	}
)

func (x AccessType) Enum() *AccessType {
	p := new(AccessType)
	*p = x
	return p
}

func (x AccessType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_fetcher_proto_enumTypes[0].Descriptor()
}

func (AccessType) Type() protoreflect.EnumType {
	return &file_api_proto_fetcher_proto_enumTypes[0]
}

func (x AccessType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessType.Descriptor instead.
func (AccessType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_fetcher_proto_rawDescGZIP(), []int{0}
}

type FetchBlobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content identifier (interpretation depends on source_type):
	// - GIT: blob SHA hash
	// - BLOB: blob hash within packager archive
	ContentId string `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	// Source type determines which backend handles the request.
	SourceType SourceType `protobuf:"varint,2,opt,name=source_type,json=sourceType,proto3,enum=monofs.SourceType" json:"source_type,omitempty"`
	// Source-specific configuration:
	// GIT: repo_url, branch, display_path
	// BLOB: storage_id
	SourceConfig map[string]string `protobuf:"bytes,3,rep,name=source_config,json=sourceConfig,proto3" json:"source_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Request metadata for tracing/metrics.
	RequestId     string `protobuf:"bytes,10,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	StorageNodeId string `protobuf:"bytes,11,opt,name=storage_node_id,json=storageNodeId,proto3" json:"storage_node_id,omitempty"`
	StorageId     string `protobuf:"bytes,12,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"` // Repository storage ID (for affinity routing)
	// Priority: 0 = highest (sync read), 10 = lowest (speculative prefetch)
	Priority      int32 `protobuf:"varint,13,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchBlobRequest) Reset() {
	*x = FetchBlobRequest{}
	mi := &file_api_proto_fetcher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchBlobRequest) ProtoMessage() {}

func (x *FetchBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fetcher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchBlobRequest.ProtoReflect.Descriptor instead.
func (*FetchBlobRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fetcher_proto_rawDescGZIP(), []int{0}
}

func (x *FetchBlobRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *FetchBlobRequest) GetSourceType() SourceType {
	if x != nil {
		return x.SourceType
	}
	return SourceType_SOURCE_TYPE_UNKNOWN
}

func (x *FetchBlobRequest) GetSourceConfig() map[string]string {
	if x != nil {
		return x.SourceConfig
	}
	return nil
}

func (x *FetchBlobRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FetchBlobRequest) GetStorageNodeId() string {
	if x != nil {
		return x.StorageNodeId
	}
	return ""
}

func (x *FetchBlobRequest) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

func (x *FetchBlobRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type FetchBlobBatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Blobs []*FetchBlobRequest    `protobuf:"bytes,1,rep,name=blobs,proto3" json:"blobs,omitempty"`
	// Max concurrent fetches (0 = use server default).
	Concurrency int32 `protobuf:"varint,2,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	// Stop on first error vs. continue and report all errors.
	FailFast      bool `protobuf:"varint,3,opt,name=fail_fast,json=failFast,proto3" json:"fail_fast,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchBlobBatchRequest) Reset() {
	*x = FetchBlobBatchRequest{}
	mi := &file_api_proto_fetcher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchBlobBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchBlobBatchRequest) ProtoMessage() {}

func (x *FetchBlobBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fetcher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchBlobBatchRequest.ProtoReflect.Descriptor instead.
func (*FetchBlobBatchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fetcher_proto_rawDescGZIP(), []int{1}
}

func (x *FetchBlobBatchRequest) GetBlobs() []*FetchBlobRequest {
	if x != nil {
		return x.Blobs
	}
	return nil
}

func (x *FetchBlobBatchRequest) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *FetchBlobBatchRequest) GetFailFast() bool {
	if x != nil {
		return x.FailFast
	}
	return false
}

type FetchBlobBatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content ID from the request.
	ContentId string `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	// Blob data (for small blobs) or empty if streaming separately.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Size in bytes.
	Size int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// True if this blob was served from fetcher's local cache.
	FromCache bool `protobuf:"varint,4,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"`
	// Fetch latency in milliseconds (0 if from cache).
	FetchLatencyMs int64 `protobuf:"varint,5,opt,name=fetch_latency_ms,json=fetchLatencyMs,proto3" json:"fetch_latency_ms,omitempty"`
	// Error message (empty on success).
	Error string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	// Indicates this is the last response in the batch.
	BatchComplete bool `protobuf:"varint,10,opt,name=batch_complete,json=batchComplete,proto3" json:"batch_complete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchBlobBatchResponse) Reset() {
	*x = FetchBlobBatchResponse{}
	mi := &file_api_proto_fetcher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchBlobBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchBlobBatchResponse) ProtoMessage() {}

func (x *FetchBlobBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fetcher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchBlobBatchResponse.ProtoReflect.Descriptor instead.
func (*FetchBlobBatchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_fetcher_proto_rawDescGZIP(), []int{2}
}

func (x *FetchBlobBatchResponse) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *FetchBlobBatchResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FetchBlobBatchResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FetchBlobBatchResponse) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

func (x *FetchBlobBatchResponse) GetFetchLatencyMs() int64 {
	if x != nil {
		return x.FetchLatencyMs
	}
	return 0
}

func (x *FetchBlobBatchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FetchBlobBatchResponse) GetBatchComplete() bool {
	if x != nil {
		return x.BatchComplete
	}
	return false
}

type PrefetchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Blobs to prefetch (same format as FetchBlobRequest).
	Blobs []*FetchBlobRequest `protobuf:"bytes,1,rep,name=blobs,proto3" json:"blobs,omitempty"`
	// Callback URL for completion notification (optional).
	// If set, fetcher will POST to this URL when prefetch completes.
	CallbackUrl string `protobuf:"bytes,2,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	// TTL for prefetched blobs in fetcher cache (seconds).
	// 0 = use server default.
	CacheTtlSeconds int32 `protobuf:"varint,3,opt,name=cache_ttl_seconds,json=cacheTtlSeconds,proto3" json:"cache_ttl_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PrefetchRequest) Reset() {
	*x = PrefetchRequest{}
	mi := &file_api_proto_fetcher_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefetchRequest) ProtoMessage() {}

func (x *PrefetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fetcher_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefetchRequest.ProtoReflect.Descriptor instead.
func (*PrefetchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fetcher_proto_rawDescGZIP(), []int{3}
}

func (x *PrefetchRequest) GetBlobs() []*FetchBlobRequest {
	if x != nil {
		return x.Blobs
	}
	return nil
}

func (x *PrefetchRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *PrefetchRequest) GetCacheTtlSeconds() int32 {
	if x != nil {
		return x.CacheTtlSeconds
	}
	return 0
}

type PrefetchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Job ID for tracking (can be used with CheckCache).
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Number of blobs accepted for prefetch.
	Accepted int32 `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// Number of blobs already cached (will skip fetch).
	AlreadyCached int32 `protobuf:"varint,3,opt,name=already_cached,json=alreadyCached,proto3" json:"already_cached,omitempty"`
	// Number of blobs rejected (invalid request, etc.).
	Rejected      int32 `protobuf:"varint,4,opt,name=rejected,proto3" json:"rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrefetchResponse) Reset() {
	*x = PrefetchResponse{}
	mi := &file_api_proto_fetcher_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefetchResponse) ProtoMessage() {}

func (x *PrefetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fetcher_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefetchResponse.ProtoReflect.Descriptor instead.
func (*PrefetchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_fetcher_proto_rawDescGZIP(), []int{4}
}

func (x *PrefetchResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *PrefetchResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *PrefetchResponse) GetAlreadyCached() int32 {
	if x != nil {
		return x.AlreadyCached
	}
	return 0
}

func (x *PrefetchResponse) GetRejected() int32 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

type CheckCacheRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content IDs to check.
	ContentIds []string `protobuf:"bytes,1,rep,name=content_ids,json=contentIds,proto3" json:"content_ids,omitempty"`
	// Source type (needed to identify cache keys).
	SourceType    SourceType `protobuf:"varint,2,opt,name=source_type,json=sourceType,proto3,enum=monofs.SourceType" json:"source_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCacheRequest) Reset() {
	*x = CheckCacheRequest{}
	mi := &file_api_proto_fetcher_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCacheRequest) ProtoMessage() {}

func (x *CheckCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fetcher_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCacheRequest.ProtoReflect.Descriptor instead.
func (*CheckCacheRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fetcher_proto_rawDescGZIP(), []int{5}
}

func (x *CheckCacheRequest) GetContentIds() []string {
	if x != nil {
		return x.ContentIds
	}
	return nil
}

func (x *CheckCacheRequest) GetSourceType() SourceType {
	if x != nil {
		return x.SourceType
	}
	return SourceType_SOURCE_TYPE_UNKNOWN
}

type CheckCacheResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of content_id -> cached (true/false).
	Cached map[string]bool `protobuf:"bytes,1,rep,name=cached,proto3" json:"cached,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Map of content_id -> size in bytes (only for cached items).
	Sizes         map[string]int64 `protobuf:"bytes,2,rep,name=sizes,proto3" json:"sizes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCacheResponse) Reset() {
	*x = CheckCacheResponse{}
	mi := &file_api_proto_fetcher_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCacheResponse) ProtoMessage() {}

func (x *CheckCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fetcher_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCacheResponse.ProtoReflect.Descriptor instead.
func (*CheckCacheResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_fetcher_proto_rawDescGZIP(), []int{6}
}

func (x *CheckCacheResponse) GetCached() map[string]bool {
	if x != nil {
		return x.Cached
	}
	return nil
}

func (x *CheckCacheResponse) GetSizes() map[string]int64 {
	if x != nil {
		return x.Sizes
	}
	return nil
}

type FetcherStatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Include detailed per-source stats.
	IncludeSourceStats bool `protobuf:"varint,1,opt,name=include_source_stats,json=includeSourceStats,proto3" json:"include_source_stats,omitempty"`
	// Include cache contents summary.
	IncludeCacheStats bool `protobuf:"varint,2,opt,name=include_cache_stats,json=includeCacheStats,proto3" json:"include_cache_stats,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FetcherStatsRequest) Reset() {
	*x = FetcherStatsRequest{}
	mi := &file_api_proto_fetcher_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetcherStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetcherStatsRequest) ProtoMessage() {}

func (x *FetcherStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fetcher_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetcherStatsRequest.ProtoReflect.Descriptor instead.
func (*FetcherStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fetcher_proto_rawDescGZIP(), []int{7}
}

func (x *FetcherStatsRequest) GetIncludeSourceStats() bool {
	if x != nil {
		return x.IncludeSourceStats
	}
	return false
}

func (x *FetcherStatsRequest) GetIncludeCacheStats() bool {
	if x != nil {
		return x.IncludeCacheStats
	}
	return false
}

type FetcherStatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fetcher instance ID.
	FetcherId string `protobuf:"bytes,1,opt,name=fetcher_id,json=fetcherId,proto3" json:"fetcher_id,omitempty"`
	// Uptime in seconds.
	UptimeSeconds int64 `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// Total requests served.
	TotalRequests int64 `protobuf:"varint,3,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	// Cache statistics.
	CacheHits      int64   `protobuf:"varint,4,opt,name=cache_hits,json=cacheHits,proto3" json:"cache_hits,omitempty"`
	CacheMisses    int64   `protobuf:"varint,5,opt,name=cache_misses,json=cacheMisses,proto3" json:"cache_misses,omitempty"`
	CacheHitRate   float64 `protobuf:"fixed64,6,opt,name=cache_hit_rate,json=cacheHitRate,proto3" json:"cache_hit_rate,omitempty"`
	CacheSizeBytes int64   `protobuf:"varint,7,opt,name=cache_size_bytes,json=cacheSizeBytes,proto3" json:"cache_size_bytes,omitempty"`
	CacheEntries   int64   `protobuf:"varint,8,opt,name=cache_entries,json=cacheEntries,proto3" json:"cache_entries,omitempty"`
	// Active operations.
	ActiveFetches    int64 `protobuf:"varint,9,opt,name=active_fetches,json=activeFetches,proto3" json:"active_fetches,omitempty"`
	QueuedPrefetches int64 `protobuf:"varint,10,opt,name=queued_prefetches,json=queuedPrefetches,proto3" json:"queued_prefetches,omitempty"`
	// Per-source statistics.
	SourceStats map[string]*SourceStats `protobuf:"bytes,11,rep,name=source_stats,json=sourceStats,proto3" json:"source_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Bytes transferred.
	BytesFetched  int64 `protobuf:"varint,12,opt,name=bytes_fetched,json=bytesFetched,proto3" json:"bytes_fetched,omitempty"`
	BytesServed   int64 `protobuf:"varint,13,opt,name=bytes_served,json=bytesServed,proto3" json:"bytes_served,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetcherStatsResponse) Reset() {
	*x = FetcherStatsResponse{}
	mi := &file_api_proto_fetcher_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetcherStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetcherStatsResponse) ProtoMessage() {}

func (x *FetcherStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fetcher_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetcherStatsResponse.ProtoReflect.Descriptor instead.
func (*FetcherStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_fetcher_proto_rawDescGZIP(), []int{8}
}

func (x *FetcherStatsResponse) GetFetcherId() string {
	if x != nil {
		return x.FetcherId
	}
	return ""
}

func (x *FetcherStatsResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *FetcherStatsResponse) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *FetcherStatsResponse) GetCacheHits() int64 {
	if x != nil {
		return x.CacheHits
	}
	return 0
}

func (x *FetcherStatsResponse) GetCacheMisses() int64 {
	if x != nil {
		return x.CacheMisses
	}
	return 0
}

func (x *FetcherStatsResponse) GetCacheHitRate() float64 {
	if x != nil {
		return x.CacheHitRate
	}
	return 0
}

func (x *FetcherStatsResponse) GetCacheSizeBytes() int64 {
	if x != nil {
		return x.CacheSizeBytes
	}
	return 0
}

func (x *FetcherStatsResponse) GetCacheEntries() int64 {
	if x != nil {
		return x.CacheEntries
	}
	return 0
}

func (x *FetcherStatsResponse) GetActiveFetches() int64 {
	if x != nil {
		return x.ActiveFetches
	}
	return 0
}

func (x *FetcherStatsResponse) GetQueuedPrefetches() int64 {
	if x != nil {
		return x.QueuedPrefetches
	}
	return 0
}

func (x *FetcherStatsResponse) GetSourceStats() map[string]*SourceStats {
	if x != nil {
		return x.SourceStats
	}
	return nil
}

func (x *FetcherStatsResponse) GetBytesFetched() int64 {
	if x != nil {
		return x.BytesFetched
	}
	return 0
}

func (x *FetcherStatsResponse) GetBytesServed() int64 {
	if x != nil {
		return x.BytesServed
	}
	return 0
}

type SourceStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      int64                  `protobuf:"varint,1,opt,name=requests,proto3" json:"requests,omitempty"`
	Errors        int64                  `protobuf:"varint,2,opt,name=errors,proto3" json:"errors,omitempty"`
	BytesFetched  int64                  `protobuf:"varint,3,opt,name=bytes_fetched,json=bytesFetched,proto3" json:"bytes_fetched,omitempty"`
	AvgLatencyMs  float64                `protobuf:"fixed64,4,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	CachedItems   int64                  `protobuf:"varint,5,opt,name=cached_items,json=cachedItems,proto3" json:"cached_items,omitempty"`
	CacheBytes    int64                  `protobuf:"varint,6,opt,name=cache_bytes,json=cacheBytes,proto3" json:"cache_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceStats) Reset() {
	*x = SourceStats{}
	mi := &file_api_proto_fetcher_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceStats) ProtoMessage() {}

func (x *SourceStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fetcher_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceStats.ProtoReflect.Descriptor instead.
func (*SourceStats) Descriptor() ([]byte, []int) {
	return file_api_proto_fetcher_proto_rawDescGZIP(), []int{9}
}

func (x *SourceStats) GetRequests() int64 {
	if x != nil {
		return x.Requests
	}
	return 0
}

func (x *SourceStats) GetErrors() int64 {
	if x != nil {
		return x.Errors
	}
	return 0
}

func (x *SourceStats) GetBytesFetched() int64 {
	if x != nil {
		return x.BytesFetched
	}
	return 0
}

func (x *SourceStats) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *SourceStats) GetCachedItems() int64 {
	if x != nil {
		return x.CachedItems
	}
	return 0
}

func (x *SourceStats) GetCacheBytes() int64 {
	if x != nil {
		return x.CacheBytes
	}
	return 0
}

// Access event reported by storage nodes for prediction training.
type AccessEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`                               // FUSE client identifier
	StorageId     string                 `protobuf:"bytes,2,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`                            // Repository storage ID
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`                               // Path within repository
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                            // Unix timestamp (nanoseconds)
	AccessType    AccessType             `protobuf:"varint,5,opt,name=access_type,json=accessType,proto3,enum=monofs.AccessType" json:"access_type,omitempty"` // Type of access
	SessionId     string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                            // Groups related accesses
	NodeId        string                 `protobuf:"bytes,7,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                                     // Storage node that served the request
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessEvent) Reset() {
	*x = AccessEvent{}
	mi := &file_api_proto_fetcher_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessEvent) ProtoMessage() {}

func (x *AccessEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fetcher_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessEvent.ProtoReflect.Descriptor instead.
func (*AccessEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_fetcher_proto_rawDescGZIP(), []int{10}
}

func (x *AccessEvent) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AccessEvent) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

func (x *AccessEvent) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *AccessEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AccessEvent) GetAccessType() AccessType {
	if x != nil {
		return x.AccessType
	}
	return AccessType_ACCESS_TYPE_UNKNOWN
}

func (x *AccessEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AccessEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// Storage nodes report access events to router for global prediction.
type ReportAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*AccessEvent         `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAccessRequest) Reset() {
	*x = ReportAccessRequest{}
	mi := &file_api_proto_fetcher_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAccessRequest) ProtoMessage() {}

func (x *ReportAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fetcher_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAccessRequest.ProtoReflect.Descriptor instead.
func (*ReportAccessRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fetcher_proto_rawDescGZIP(), []int{11}
}

func (x *ReportAccessRequest) GetEvents() []*AccessEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ReportAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int32                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAccessResponse) Reset() {
	*x = ReportAccessResponse{}
	mi := &file_api_proto_fetcher_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAccessResponse) ProtoMessage() {}

func (x *ReportAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fetcher_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAccessResponse.ProtoReflect.Descriptor instead.
func (*ReportAccessResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_fetcher_proto_rawDescGZIP(), []int{12}
}

func (x *ReportAccessResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

// Request predictions for a file (what should be prefetched next).
type GetPredictionsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StorageId      string                 `protobuf:"bytes,1,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	FilePath       string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	ClientId       string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	MaxResults     int32                  `protobuf:"varint,4,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	MinProbability float32                `protobuf:"fixed32,5,opt,name=min_probability,json=minProbability,proto3" json:"min_probability,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPredictionsRequest) Reset() {
	*x = GetPredictionsRequest{}
	mi := &file_api_proto_fetcher_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPredictionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredictionsRequest) ProtoMessage() {}

func (x *GetPredictionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fetcher_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredictionsRequest.ProtoReflect.Descriptor instead.
func (*GetPredictionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fetcher_proto_rawDescGZIP(), []int{13}
}

func (x *GetPredictionsRequest) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

func (x *GetPredictionsRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *GetPredictionsRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GetPredictionsRequest) GetMaxResults() int32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

func (x *GetPredictionsRequest) GetMinProbability() float32 {
	if x != nil {
		return x.MinProbability
	}
	return 0
}

type GetPredictionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Predictions   []*PredictedFile       `protobuf:"bytes,1,rep,name=predictions,proto3" json:"predictions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPredictionsResponse) Reset() {
	*x = GetPredictionsResponse{}
	mi := &file_api_proto_fetcher_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPredictionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredictionsResponse) ProtoMessage() {}

func (x *GetPredictionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fetcher_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredictionsResponse.ProtoReflect.Descriptor instead.
func (*GetPredictionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_fetcher_proto_rawDescGZIP(), []int{14}
}

func (x *GetPredictionsResponse) GetPredictions() []*PredictedFile {
	if x != nil {
		return x.Predictions
	}
	return nil
}

type PredictedFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StorageId     string                 `protobuf:"bytes,1,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Probability   float32                `protobuf:"fixed32,3,opt,name=probability,proto3" json:"probability,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`                                                   // "markov", "cluster", "structural", "temporal"
	ContentId     string                 `protobuf:"bytes,5,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`                            // Blob hash for fetching
	SourceType    SourceType             `protobuf:"varint,6,opt,name=source_type,json=sourceType,proto3,enum=monofs.SourceType" json:"source_type,omitempty"` // How to fetch
	SourceConfig  map[string]string      `protobuf:"bytes,7,rep,name=source_config,json=sourceConfig,proto3" json:"source_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictedFile) Reset() {
	*x = PredictedFile{}
	mi := &file_api_proto_fetcher_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictedFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictedFile) ProtoMessage() {}

func (x *PredictedFile) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fetcher_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictedFile.ProtoReflect.Descriptor instead.
func (*PredictedFile) Descriptor() ([]byte, []int) {
	return file_api_proto_fetcher_proto_rawDescGZIP(), []int{15}
}

func (x *PredictedFile) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

func (x *PredictedFile) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *PredictedFile) GetProbability() float32 {
	if x != nil {
		return x.Probability
	}
	return 0
}

func (x *PredictedFile) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PredictedFile) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *PredictedFile) GetSourceType() SourceType {
	if x != nil {
		return x.SourceType
	}
	return SourceType_SOURCE_TYPE_UNKNOWN
}

func (x *PredictedFile) GetSourceConfig() map[string]string {
	if x != nil {
		return x.SourceConfig
	}
	return nil
}

// StoreBlob stores a single blob on the fetcher.
type StoreBlobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SHA-256 hash of the blob content (used as storage key).
	BlobHash string `protobuf:"bytes,1,opt,name=blob_hash,json=blobHash,proto3" json:"blob_hash,omitempty"`
	// Raw blob content.
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Request ID for tracing.
	RequestId     string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreBlobRequest) Reset() {
	*x = StoreBlobRequest{}
	mi := &file_api_proto_fetcher_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreBlobRequest) ProtoMessage() {}

func (x *StoreBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fetcher_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreBlobRequest.ProtoReflect.Descriptor instead.
func (*StoreBlobRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fetcher_proto_rawDescGZIP(), []int{16}
}

func (x *StoreBlobRequest) GetBlobHash() string {
	if x != nil {
		return x.BlobHash
	}
	return ""
}

func (x *StoreBlobRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *StoreBlobRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type StoreBlobResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Success      bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Size of stored blob in bytes.
	Size          int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreBlobResponse) Reset() {
	*x = StoreBlobResponse{}
	mi := &file_api_proto_fetcher_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreBlobResponse) ProtoMessage() {}

func (x *StoreBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fetcher_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreBlobResponse.ProtoReflect.Descriptor instead.
func (*StoreBlobResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_fetcher_proto_rawDescGZIP(), []int{17}
}

func (x *StoreBlobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreBlobResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StoreBlobResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// StoreArchiveChunk streams a packager archive to the fetcher.
// The first chunk must contain the header with storage_id.
type StoreArchiveChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Storage ID this archive belongs to (set in first chunk).
	StorageId string `protobuf:"bytes,1,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	// Archive chunk index (for split archives, 0-based).
	ChunkIndex int32 `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	// Raw archive data.
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// True if this is the last chunk of this archive piece.
	IsLast        bool `protobuf:"varint,4,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreArchiveChunk) Reset() {
	*x = StoreArchiveChunk{}
	mi := &file_api_proto_fetcher_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreArchiveChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreArchiveChunk) ProtoMessage() {}

func (x *StoreArchiveChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fetcher_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreArchiveChunk.ProtoReflect.Descriptor instead.
func (*StoreArchiveChunk) Descriptor() ([]byte, []int) {
	return file_api_proto_fetcher_proto_rawDescGZIP(), []int{18}
}

func (x *StoreArchiveChunk) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

func (x *StoreArchiveChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *StoreArchiveChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StoreArchiveChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

type StoreArchiveResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Success      bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Total bytes stored.
	TotalBytes int64 `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	// Number of files indexed from the archive.
	FilesIndexed  int64 `protobuf:"varint,4,opt,name=files_indexed,json=filesIndexed,proto3" json:"files_indexed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreArchiveResponse) Reset() {
	*x = StoreArchiveResponse{}
	mi := &file_api_proto_fetcher_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreArchiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreArchiveResponse) ProtoMessage() {}

func (x *StoreArchiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fetcher_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreArchiveResponse.ProtoReflect.Descriptor instead.
func (*StoreArchiveResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_fetcher_proto_rawDescGZIP(), []int{19}
}

func (x *StoreArchiveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreArchiveResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StoreArchiveResponse) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *StoreArchiveResponse) GetFilesIndexed() int64 {
	if x != nil {
		return x.FilesIndexed
	}
	return 0
}

// StoreBlobEntry is a single blob (or chunk of a blob) sent in a
// StoreBlobBatchStream.  Small blobs are sent as one message with
// chunk_index=0 and is_last=true (the default).  Large blobs are
// split across multiple messages sharing the same blob_hash;
// chunk_index increments from 0 and the final chunk sets is_last=true.
type StoreBlobEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SHA-256 hash of the full blob content (used as storage/index key).
	BlobHash string `protobuf:"bytes,1,opt,name=blob_hash,json=blobHash,proto3" json:"blob_hash,omitempty"`
	// Raw blob content (or a chunk of it for large blobs).
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Chunk sequence number within this blob (0-based).
	ChunkIndex int32 `protobuf:"varint,3,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	// True when this is the last (or only) chunk for this blob_hash.
	IsLast bool `protobuf:"varint,4,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	// Total uncompressed size of the complete blob in bytes.
	// Only required on the first chunk (chunk_index == 0).
	TotalSize     int64 `protobuf:"varint,5,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreBlobEntry) Reset() {
	*x = StoreBlobEntry{}
	mi := &file_api_proto_fetcher_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreBlobEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreBlobEntry) ProtoMessage() {}

func (x *StoreBlobEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fetcher_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreBlobEntry.ProtoReflect.Descriptor instead.
func (*StoreBlobEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_fetcher_proto_rawDescGZIP(), []int{20}
}

func (x *StoreBlobEntry) GetBlobHash() string {
	if x != nil {
		return x.BlobHash
	}
	return ""
}

func (x *StoreBlobEntry) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *StoreBlobEntry) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *StoreBlobEntry) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *StoreBlobEntry) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// StoreBlobBatchResponse summarises the streaming batch storage operation.
type StoreBlobBatchResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Success      bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Number of blobs written to archive(s).
	Stored int32 `protobuf:"varint,3,opt,name=stored,proto3" json:"stored,omitempty"`
	// Number of blobs skipped (already indexed).
	Skipped int32 `protobuf:"varint,4,opt,name=skipped,proto3" json:"skipped,omitempty"`
	// Number of blobs that failed.
	Failed int32 `protobuf:"varint,5,opt,name=failed,proto3" json:"failed,omitempty"`
	// Total archive bytes written to disk.
	ArchiveBytes int64 `protobuf:"varint,6,opt,name=archive_bytes,json=archiveBytes,proto3" json:"archive_bytes,omitempty"`
	// Number of archive files created.
	ArchivesCreated int32 `protobuf:"varint,7,opt,name=archives_created,json=archivesCreated,proto3" json:"archives_created,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StoreBlobBatchResponse) Reset() {
	*x = StoreBlobBatchResponse{}
	mi := &file_api_proto_fetcher_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreBlobBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreBlobBatchResponse) ProtoMessage() {}

func (x *StoreBlobBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fetcher_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreBlobBatchResponse.ProtoReflect.Descriptor instead.
func (*StoreBlobBatchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_fetcher_proto_rawDescGZIP(), []int{21}
}

func (x *StoreBlobBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreBlobBatchResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StoreBlobBatchResponse) GetStored() int32 {
	if x != nil {
		return x.Stored
	}
	return 0
}

func (x *StoreBlobBatchResponse) GetSkipped() int32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

func (x *StoreBlobBatchResponse) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *StoreBlobBatchResponse) GetArchiveBytes() int64 {
	if x != nil {
		return x.ArchiveBytes
	}
	return 0
}

func (x *StoreBlobBatchResponse) GetArchivesCreated() int32 {
	if x != nil {
		return x.ArchivesCreated
	}
	return 0
}

// DeleteBlobsRequest asks the fetcher to remove blobs from its index.
type DeleteBlobsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SHA-256 hashes of blobs to delete.
	BlobHashes []string `protobuf:"bytes,1,rep,name=blob_hashes,json=blobHashes,proto3" json:"blob_hashes,omitempty"`
	// When true, also remove archive files that become empty after
	// deleting these entries (compaction). Default false.
	Compact       bool `protobuf:"varint,2,opt,name=compact,proto3" json:"compact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlobsRequest) Reset() {
	*x = DeleteBlobsRequest{}
	mi := &file_api_proto_fetcher_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlobsRequest) ProtoMessage() {}

func (x *DeleteBlobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fetcher_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlobsRequest.ProtoReflect.Descriptor instead.
func (*DeleteBlobsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fetcher_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteBlobsRequest) GetBlobHashes() []string {
	if x != nil {
		return x.BlobHashes
	}
	return nil
}

func (x *DeleteBlobsRequest) GetCompact() bool {
	if x != nil {
		return x.Compact
	}
	return false
}

// DeleteBlobsResponse reports how many blobs were deleted.
type DeleteBlobsResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Success      bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Number of blobs removed from the index.
	Deleted int32 `protobuf:"varint,3,opt,name=deleted,proto3" json:"deleted,omitempty"`
	// Number of hashes not found in the index.
	NotFound int32 `protobuf:"varint,4,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	// Number of archive files removed during compaction.
	ArchivesRemoved int32 `protobuf:"varint,5,opt,name=archives_removed,json=archivesRemoved,proto3" json:"archives_removed,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteBlobsResponse) Reset() {
	*x = DeleteBlobsResponse{}
	mi := &file_api_proto_fetcher_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlobsResponse) ProtoMessage() {}

func (x *DeleteBlobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fetcher_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlobsResponse.ProtoReflect.Descriptor instead.
func (*DeleteBlobsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_fetcher_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteBlobsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteBlobsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DeleteBlobsResponse) GetDeleted() int32 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *DeleteBlobsResponse) GetNotFound() int32 {
	if x != nil {
		return x.NotFound
	}
	return 0
}

func (x *DeleteBlobsResponse) GetArchivesRemoved() int32 {
	if x != nil {
		return x.ArchivesRemoved
	}
	return 0
}

var File_api_proto_fetcher_proto protoreflect.FileDescriptor

const file_api_proto_fetcher_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/fetcher.proto\x12\x06monofs\x1a\x16api/proto/monofs.proto\"\xfa\x02\n" +
	"\x10FetchBlobRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x123\n" +
	"\vsource_type\x18\x02 \x01(\x0e2\x12.monofs.SourceTypeR\n" +
	"sourceType\x12O\n" +
	"\rsource_config\x18\x03 \x03(\v2*.monofs.FetchBlobRequest.SourceConfigEntryR\fsourceConfig\x12\x1d\n" +
	"\n" +
	"request_id\x18\n" +
	" \x01(\tR\trequestId\x12&\n" +
	"\x0fstorage_node_id\x18\v \x01(\tR\rstorageNodeId\x12\x1d\n" +
	"\n" +
	"storage_id\x18\f \x01(\tR\tstorageId\x12\x1a\n" +
	"\bpriority\x18\r \x01(\x05R\bpriority\x1a?\n" +
	"\x11SourceConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x01\n" +
	"\x15FetchBlobBatchRequest\x12.\n" +
	"\x05blobs\x18\x01 \x03(\v2\x18.monofs.FetchBlobRequestR\x05blobs\x12 \n" +
	"\vconcurrency\x18\x02 \x01(\x05R\vconcurrency\x12\x1b\n" +
	"\tfail_fast\x18\x03 \x01(\bR\bfailFast\"\xe5\x01\n" +
	"\x16FetchBlobBatchResponse\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x1d\n" +
	"\n" +
	"from_cache\x18\x04 \x01(\bR\tfromCache\x12(\n" +
	"\x10fetch_latency_ms\x18\x05 \x01(\x03R\x0efetchLatencyMs\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12%\n" +
	"\x0ebatch_complete\x18\n" +
	" \x01(\bR\rbatchComplete\"\x90\x01\n" +
	"\x0fPrefetchRequest\x12.\n" +
	"\x05blobs\x18\x01 \x03(\v2\x18.monofs.FetchBlobRequestR\x05blobs\x12!\n" +
	"\fcallback_url\x18\x02 \x01(\tR\vcallbackUrl\x12*\n" +
	"\x11cache_ttl_seconds\x18\x03 \x01(\x05R\x0fcacheTtlSeconds\"\x88\x01\n" +
	"\x10PrefetchResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\x05R\baccepted\x12%\n" +
	"\x0ealready_cached\x18\x03 \x01(\x05R\ralreadyCached\x12\x1a\n" +
	"\brejected\x18\x04 \x01(\x05R\brejected\"i\n" +
	"\x11CheckCacheRequest\x12\x1f\n" +
	"\vcontent_ids\x18\x01 \x03(\tR\n" +
	"contentIds\x123\n" +
	"\vsource_type\x18\x02 \x01(\x0e2\x12.monofs.SourceTypeR\n" +
	"sourceType\"\x86\x02\n" +
	"\x12CheckCacheResponse\x12>\n" +
	"\x06cached\x18\x01 \x03(\v2&.monofs.CheckCacheResponse.CachedEntryR\x06cached\x12;\n" +
	"\x05sizes\x18\x02 \x03(\v2%.monofs.CheckCacheResponse.SizesEntryR\x05sizes\x1a9\n" +
	"\vCachedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"SizesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"w\n" +
	"\x13FetcherStatsRequest\x120\n" +
	"\x14include_source_stats\x18\x01 \x01(\bR\x12includeSourceStats\x12.\n" +
	"\x13include_cache_stats\x18\x02 \x01(\bR\x11includeCacheStats\"\xfd\x04\n" +
	"\x14FetcherStatsResponse\x12\x1d\n" +
	"\n" +
	"fetcher_id\x18\x01 \x01(\tR\tfetcherId\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12%\n" +
	"\x0etotal_requests\x18\x03 \x01(\x03R\rtotalRequests\x12\x1d\n" +
	"\n" +
	"cache_hits\x18\x04 \x01(\x03R\tcacheHits\x12!\n" +
	"\fcache_misses\x18\x05 \x01(\x03R\vcacheMisses\x12$\n" +
	"\x0ecache_hit_rate\x18\x06 \x01(\x01R\fcacheHitRate\x12(\n" +
	"\x10cache_size_bytes\x18\a \x01(\x03R\x0ecacheSizeBytes\x12#\n" +
	"\rcache_entries\x18\b \x01(\x03R\fcacheEntries\x12%\n" +
	"\x0eactive_fetches\x18\t \x01(\x03R\ractiveFetches\x12+\n" +
	"\x11queued_prefetches\x18\n" +
	" \x01(\x03R\x10queuedPrefetches\x12P\n" +
	"\fsource_stats\x18\v \x03(\v2-.monofs.FetcherStatsResponse.SourceStatsEntryR\vsourceStats\x12#\n" +
	"\rbytes_fetched\x18\f \x01(\x03R\fbytesFetched\x12!\n" +
	"\fbytes_served\x18\r \x01(\x03R\vbytesServed\x1aS\n" +
	"\x10SourceStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.monofs.SourceStatsR\x05value:\x028\x01\"\xd0\x01\n" +
	"\vSourceStats\x12\x1a\n" +
	"\brequests\x18\x01 \x01(\x03R\brequests\x12\x16\n" +
	"\x06errors\x18\x02 \x01(\x03R\x06errors\x12#\n" +
	"\rbytes_fetched\x18\x03 \x01(\x03R\fbytesFetched\x12$\n" +
	"\x0eavg_latency_ms\x18\x04 \x01(\x01R\favgLatencyMs\x12!\n" +
	"\fcached_items\x18\x05 \x01(\x03R\vcachedItems\x12\x1f\n" +
	"\vcache_bytes\x18\x06 \x01(\x03R\n" +
	"cacheBytes\"\xf1\x01\n" +
	"\vAccessEvent\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"storage_id\x18\x02 \x01(\tR\tstorageId\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x123\n" +
	"\vaccess_type\x18\x05 \x01(\x0e2\x12.monofs.AccessTypeR\n" +
	"accessType\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12\x17\n" +
	"\anode_id\x18\a \x01(\tR\x06nodeId\"B\n" +
	"\x13ReportAccessRequest\x12+\n" +
	"\x06events\x18\x01 \x03(\v2\x13.monofs.AccessEventR\x06events\"2\n" +
	"\x14ReportAccessResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x05R\baccepted\"\xba\x01\n" +
	"\x15GetPredictionsRequest\x12\x1d\n" +
	"\n" +
	"storage_id\x18\x01 \x01(\tR\tstorageId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x1f\n" +
	"\vmax_results\x18\x04 \x01(\x05R\n" +
	"maxResults\x12'\n" +
	"\x0fmin_probability\x18\x05 \x01(\x02R\x0eminProbability\"Q\n" +
	"\x16GetPredictionsResponse\x127\n" +
	"\vpredictions\x18\x01 \x03(\v2\x15.monofs.PredictedFileR\vpredictions\"\xe8\x02\n" +
	"\rPredictedFile\x12\x1d\n" +
	"\n" +
	"storage_id\x18\x01 \x01(\tR\tstorageId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12 \n" +
	"\vprobability\x18\x03 \x01(\x02R\vprobability\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"content_id\x18\x05 \x01(\tR\tcontentId\x123\n" +
	"\vsource_type\x18\x06 \x01(\x0e2\x12.monofs.SourceTypeR\n" +
	"sourceType\x12L\n" +
	"\rsource_config\x18\a \x03(\v2'.monofs.PredictedFile.SourceConfigEntryR\fsourceConfig\x1a?\n" +
	"\x11SourceConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"h\n" +
	"\x10StoreBlobRequest\x12\x1b\n" +
	"\tblob_hash\x18\x01 \x01(\tR\bblobHash\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"f\n" +
	"\x11StoreBlobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"\x80\x01\n" +
	"\x11StoreArchiveChunk\x12\x1d\n" +
	"\n" +
	"storage_id\x18\x01 \x01(\tR\tstorageId\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x17\n" +
	"\ais_last\x18\x04 \x01(\bR\x06isLast\"\x9b\x01\n" +
	"\x14StoreArchiveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x03R\n" +
	"totalBytes\x12#\n" +
	"\rfiles_indexed\x18\x04 \x01(\x03R\ffilesIndexed\"\xa0\x01\n" +
	"\x0eStoreBlobEntry\x12\x1b\n" +
	"\tblob_hash\x18\x01 \x01(\tR\bblobHash\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x1f\n" +
	"\vchunk_index\x18\x03 \x01(\x05R\n" +
	"chunkIndex\x12\x17\n" +
	"\ais_last\x18\x04 \x01(\bR\x06isLast\x12\x1d\n" +
	"\n" +
	"total_size\x18\x05 \x01(\x03R\ttotalSize\"\xf1\x01\n" +
	"\x16StoreBlobBatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x16\n" +
	"\x06stored\x18\x03 \x01(\x05R\x06stored\x12\x18\n" +
	"\askipped\x18\x04 \x01(\x05R\askipped\x12\x16\n" +
	"\x06failed\x18\x05 \x01(\x05R\x06failed\x12#\n" +
	"\rarchive_bytes\x18\x06 \x01(\x03R\farchiveBytes\x12)\n" +
	"\x10archives_created\x18\a \x01(\x05R\x0farchivesCreated\"O\n" +
	"\x12DeleteBlobsRequest\x12\x1f\n" +
	"\vblob_hashes\x18\x01 \x03(\tR\n" +
	"blobHashes\x12\x18\n" +
	"\acompact\x18\x02 \x01(\bR\acompact\"\xb6\x01\n" +
	"\x13DeleteBlobsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x18\n" +
	"\adeleted\x18\x03 \x01(\x05R\adeleted\x12\x1b\n" +
	"\tnot_found\x18\x04 \x01(\x05R\bnotFound\x12)\n" +
	"\x10archives_removed\x18\x05 \x01(\x05R\x0farchivesRemoved*\x85\x01\n" +
	"\n" +
	"AccessType\x12\x17\n" +
	"\x13ACCESS_TYPE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10ACCESS_TYPE_READ\x10\x01\x12\x17\n" +
	"\x13ACCESS_TYPE_READDIR\x10\x02\x12\x16\n" +
	"\x12ACCESS_TYPE_LOOKUP\x10\x03\x12\x17\n" +
	"\x13ACCESS_TYPE_GETATTR\x10\x042\x93\x05\n" +
	"\vBlobFetcher\x12:\n" +
	"\tFetchBlob\x12\x18.monofs.FetchBlobRequest\x1a\x11.monofs.DataChunk0\x01\x12Q\n" +
	"\x0eFetchBlobBatch\x12\x1d.monofs.FetchBlobBatchRequest\x1a\x1e.monofs.FetchBlobBatchResponse0\x01\x12B\n" +
	"\rPrefetchBlobs\x12\x17.monofs.PrefetchRequest\x1a\x18.monofs.PrefetchResponse\x12C\n" +
	"\n" +
	"CheckCache\x12\x19.monofs.CheckCacheRequest\x1a\x1a.monofs.CheckCacheResponse\x12E\n" +
	"\bGetStats\x12\x1b.monofs.FetcherStatsRequest\x1a\x1c.monofs.FetcherStatsResponse\x12@\n" +
	"\tStoreBlob\x12\x18.monofs.StoreBlobRequest\x1a\x19.monofs.StoreBlobResponse\x12P\n" +
	"\x14StoreBlobBatchStream\x12\x16.monofs.StoreBlobEntry\x1a\x1e.monofs.StoreBlobBatchResponse(\x01\x12F\n" +
	"\vDeleteBlobs\x12\x1a.monofs.DeleteBlobsRequest\x1a\x1b.monofs.DeleteBlobsResponse\x12I\n" +
	"\fStoreArchive\x12\x19.monofs.StoreArchiveChunk\x1a\x1c.monofs.StoreArchiveResponse(\x01B$Z\"github.com/radryc/monofs/api/protob\x06proto3"

var (
	file_api_proto_fetcher_proto_rawDescOnce sync.Once
	file_api_proto_fetcher_proto_rawDescData []byte
)

func file_api_proto_fetcher_proto_rawDescGZIP() []byte {
	file_api_proto_fetcher_proto_rawDescOnce.Do(func() {
		file_api_proto_fetcher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_fetcher_proto_rawDesc), len(file_api_proto_fetcher_proto_rawDesc)))
	})
	return file_api_proto_fetcher_proto_rawDescData
}

var file_api_proto_fetcher_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_fetcher_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_api_proto_fetcher_proto_goTypes = []any{
	(AccessType)(0),                // 0: monofs.AccessType
	(*FetchBlobRequest)(nil),       // 1: monofs.FetchBlobRequest
	(*FetchBlobBatchRequest)(nil),  // 2: monofs.FetchBlobBatchRequest
	(*FetchBlobBatchResponse)(nil), // 3: monofs.FetchBlobBatchResponse
	(*PrefetchRequest)(nil),        // 4: monofs.PrefetchRequest
	(*PrefetchResponse)(nil),       // 5: monofs.PrefetchResponse
	(*CheckCacheRequest)(nil),      // 6: monofs.CheckCacheRequest
	(*CheckCacheResponse)(nil),     // 7: monofs.CheckCacheResponse
	(*FetcherStatsRequest)(nil),    // 8: monofs.FetcherStatsRequest
	(*FetcherStatsResponse)(nil),   // 9: monofs.FetcherStatsResponse
	(*SourceStats)(nil),            // 10: monofs.SourceStats
	(*AccessEvent)(nil),            // 11: monofs.AccessEvent
	(*ReportAccessRequest)(nil),    // 12: monofs.ReportAccessRequest
	(*ReportAccessResponse)(nil),   // 13: monofs.ReportAccessResponse
	(*GetPredictionsRequest)(nil),  // 14: monofs.GetPredictionsRequest
	(*GetPredictionsResponse)(nil), // 15: monofs.GetPredictionsResponse
	(*PredictedFile)(nil),          // 16: monofs.PredictedFile
	(*StoreBlobRequest)(nil),       // 17: monofs.StoreBlobRequest
	(*StoreBlobResponse)(nil),      // 18: monofs.StoreBlobResponse
	(*StoreArchiveChunk)(nil),      // 19: monofs.StoreArchiveChunk
	(*StoreArchiveResponse)(nil),   // 20: monofs.StoreArchiveResponse
	(*StoreBlobEntry)(nil),         // 21: monofs.StoreBlobEntry
	(*StoreBlobBatchResponse)(nil), // 22: monofs.StoreBlobBatchResponse
	(*DeleteBlobsRequest)(nil),     // 23: monofs.DeleteBlobsRequest
	(*DeleteBlobsResponse)(nil),    // 24: monofs.DeleteBlobsResponse
	nil,                            // 25: monofs.FetchBlobRequest.SourceConfigEntry
	nil,                            // 26: monofs.CheckCacheResponse.CachedEntry
	nil,                            // 27: monofs.CheckCacheResponse.SizesEntry
	nil,                            // 28: monofs.FetcherStatsResponse.SourceStatsEntry
	nil,                            // 29: monofs.PredictedFile.SourceConfigEntry
	(SourceType)(0),                // 30: monofs.SourceType
	(*DataChunk)(nil),              // 31: monofs.DataChunk
}
var file_api_proto_fetcher_proto_depIdxs = []int32{
	30, // 0: monofs.FetchBlobRequest.source_type:type_name -> monofs.SourceType
	25, // 1: monofs.FetchBlobRequest.source_config:type_name -> monofs.FetchBlobRequest.SourceConfigEntry
	1,  // 2: monofs.FetchBlobBatchRequest.blobs:type_name -> monofs.FetchBlobRequest
	1,  // 3: monofs.PrefetchRequest.blobs:type_name -> monofs.FetchBlobRequest
	30, // 4: monofs.CheckCacheRequest.source_type:type_name -> monofs.SourceType
	26, // 5: monofs.CheckCacheResponse.cached:type_name -> monofs.CheckCacheResponse.CachedEntry
	27, // 6: monofs.CheckCacheResponse.sizes:type_name -> monofs.CheckCacheResponse.SizesEntry
	28, // 7: monofs.FetcherStatsResponse.source_stats:type_name -> monofs.FetcherStatsResponse.SourceStatsEntry
	0,  // 8: monofs.AccessEvent.access_type:type_name -> monofs.AccessType
	11, // 9: monofs.ReportAccessRequest.events:type_name -> monofs.AccessEvent
	16, // 10: monofs.GetPredictionsResponse.predictions:type_name -> monofs.PredictedFile
	30, // 11: monofs.PredictedFile.source_type:type_name -> monofs.SourceType
	29, // 12: monofs.PredictedFile.source_config:type_name -> monofs.PredictedFile.SourceConfigEntry
	10, // 13: monofs.FetcherStatsResponse.SourceStatsEntry.value:type_name -> monofs.SourceStats
	1,  // 14: monofs.BlobFetcher.FetchBlob:input_type -> monofs.FetchBlobRequest
	2,  // 15: monofs.BlobFetcher.FetchBlobBatch:input_type -> monofs.FetchBlobBatchRequest
	4,  // 16: monofs.BlobFetcher.PrefetchBlobs:input_type -> monofs.PrefetchRequest
	6,  // 17: monofs.BlobFetcher.CheckCache:input_type -> monofs.CheckCacheRequest
	8,  // 18: monofs.BlobFetcher.GetStats:input_type -> monofs.FetcherStatsRequest
	17, // 19: monofs.BlobFetcher.StoreBlob:input_type -> monofs.StoreBlobRequest
	21, // 20: monofs.BlobFetcher.StoreBlobBatchStream:input_type -> monofs.StoreBlobEntry
	23, // 21: monofs.BlobFetcher.DeleteBlobs:input_type -> monofs.DeleteBlobsRequest
	19, // 22: monofs.BlobFetcher.StoreArchive:input_type -> monofs.StoreArchiveChunk
	31, // 23: monofs.BlobFetcher.FetchBlob:output_type -> monofs.DataChunk
	3,  // 24: monofs.BlobFetcher.FetchBlobBatch:output_type -> monofs.FetchBlobBatchResponse
	5,  // 25: monofs.BlobFetcher.PrefetchBlobs:output_type -> monofs.PrefetchResponse
	7,  // 26: monofs.BlobFetcher.CheckCache:output_type -> monofs.CheckCacheResponse
	9,  // 27: monofs.BlobFetcher.GetStats:output_type -> monofs.FetcherStatsResponse
	18, // 28: monofs.BlobFetcher.StoreBlob:output_type -> monofs.StoreBlobResponse
	22, // 29: monofs.BlobFetcher.StoreBlobBatchStream:output_type -> monofs.StoreBlobBatchResponse
	24, // 30: monofs.BlobFetcher.DeleteBlobs:output_type -> monofs.DeleteBlobsResponse
	20, // 31: monofs.BlobFetcher.StoreArchive:output_type -> monofs.StoreArchiveResponse
	23, // [23:32] is the sub-list for method output_type
	14, // [14:23] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_proto_fetcher_proto_init() }
func file_api_proto_fetcher_proto_init() {
	if File_api_proto_fetcher_proto != nil {
		return
	}
	file_api_proto_monofs_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_fetcher_proto_rawDesc), len(file_api_proto_fetcher_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_fetcher_proto_goTypes,
		DependencyIndexes: file_api_proto_fetcher_proto_depIdxs,
		EnumInfos:         file_api_proto_fetcher_proto_enumTypes,
		MessageInfos:      file_api_proto_fetcher_proto_msgTypes,
	}.Build()
	File_api_proto_fetcher_proto = out.File
	file_api_proto_fetcher_proto_goTypes = nil
	file_api_proto_fetcher_proto_depIdxs = nil
}
