package bazel

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// GeneratedFiles holds the content of each generated file.
type GeneratedFiles struct {
	Bazelversion string
	Bazelrc      string
	ModuleBazel  string
	Workspace    string
	BuildBazel   string
}

// Generate reads the workspace manifest from a file (or raw JSON) and
// returns the content for all synthetic Bazel files.
//
// The caller is responsible for writing these to the mount root.
func (g *Generator) Generate(ctx context.Context, manifest *WorkspaceManifest) (*GeneratedFiles, error) {
	if manifest == nil {
		return nil, fmt.Errorf("manifest is nil")
	}
	repos := manifest.IncludedRepos()

	files := &GeneratedFiles{}

	if v := g.bazelVersion(); v != "" {
		files.Bazelversion = v + "\n"
	}
	files.Bazelrc = g.generateBazelrc(repos)
	files.ModuleBazel = g.generateModuleBazel(repos)
	files.Workspace = g.generateWorkspace(repos)
	files.BuildBazel = g.generateRootBuild(repos)

	return files, nil
}

// WriteGeneratedFiles writes the generated content into the mount root.
// Returns the list of files written (relative to MountRoot).
func (g *Generator) WriteGeneratedFiles(ctx context.Context, manifest *WorkspaceManifest) ([]string, error) {
	files, err := g.Generate(ctx, manifest)
	if err != nil {
		return nil, err
	}
	root := g.mountRoot()

	out := map[string]string{
		".bazelversion": files.Bazelversion,
		".bazelrc":      files.Bazelrc,
		"MODULE.bazel":  files.ModuleBazel,
		"WORKSPACE":     files.Workspace,
		"BUILD.bazel":   files.BuildBazel,
	}

	var written []string
	for name, content := range out {
		if content == "" {
			continue
		}
		path := filepath.Join(root, name)
		if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
			return written, fmt.Errorf("mkdir for %s: %w", name, err)
		}
		// Only write if content changed (preserve mtime when unchanged).
		existing, _ := os.ReadFile(path)
		if string(existing) == content {
			written = append(written, name)
			continue
		}
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return written, fmt.Errorf("write %s: %w", name, err)
		}
		written = append(written, name)
	}
	return written, nil
}

// LoadManifest reads and parses a workspace.json file.
func LoadManifest(path string) (*WorkspaceManifest, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read manifest %s: %w", path, err)
	}
	return ParseManifest(data)
}

// ParseManifest parses workspace.json content.
func ParseManifest(data []byte) (*WorkspaceManifest, error) {
	var m WorkspaceManifest
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, fmt.Errorf("parse manifest: %w", err)
	}
	return &m, nil
}

// ManifestInputHash returns a stable SHA-256 hash of manifest fields that
// affect generated output. The caller can use this to skip regeneration
// when the workspace hasn't changed.
func ManifestInputHash(manifest *WorkspaceManifest) string {
	if manifest == nil {
		return ""
	}
	h := sha256.New()
	repos := manifest.IncludedRepos()
	sort.Slice(repos, func(i, j int) bool {
		return repos[i].DisplayPath < repos[j].DisplayPath
	})
	for _, r := range repos {
		h.Write([]byte(r.DisplayPath))
		h.Write([]byte("\x00"))
		h.Write([]byte(r.Source))
		h.Write([]byte("\x00"))
	}
	return hex.EncodeToString(h.Sum(nil))
}

// --- private helpers ---

func (g *Generator) mountRoot() string {
	if g.MountRoot != "" {
		return g.MountRoot
	}
	return "."
}

func (g *Generator) bazelVersion() string {
	if g.BazelVersion != "" {
		return g.BazelVersion
	}
	return DefaultBazelVersion
}

func (g *Generator) generateBazelrc(repos []ManifestRepository) string {
	var b strings.Builder
	b.WriteString("# Generated by monofs-bazelctl -- DO NOT EDIT\n")
	b.WriteString("# Regenerate: monofs-bazelctl sync\n")
	b.WriteString(fmt.Sprintf("# Generated at: %s\n", time.Now().UTC().Format(time.RFC3339)))
	b.WriteString("\n")
	b.WriteString("# Common configuration for all MonoFS Bazel users.\n")
	b.WriteString("\n")

	// Output base
	b.WriteString("# Keep Bazel output in the overlay, not /tmp.\n")
	b.WriteString("startup --output_user_root=/home/monofs/.cache/bazel\n")
	b.WriteString("\n")

	// Disk cache fallback
	b.WriteString("# Local disk cache as fallback.\n")
	b.WriteString("build --disk_cache=/home/monofs/.cache/bazel-disk\n")
	b.WriteString("\n")

	// Remote cache
	if g.CacheEnabled && g.CacheAddr != "" {
		b.WriteString("# Remote cache (monofs-cache).\n")
		b.WriteString(fmt.Sprintf("build:remote-cache --remote_cache=http://%s\n", g.CacheAddr))
		b.WriteString("build:remote-cache --remote_timeout=120\n")
		b.WriteString("build:remote-cache --remote_upload_local_results=true\n")
		b.WriteString("\n")
	}

	// Remote execution
	if g.ExecutorEnabled && g.ExecutorAddr != "" {
		b.WriteString("# Remote execution (monofs-executor).\n")
		b.WriteString(fmt.Sprintf("build:remote-exec --remote_executor=grpc://%s\n", g.ExecutorAddr))
		b.WriteString("build:remote-exec --remote_default_platform_properties=properties:{\n")
		b.WriteString("  name:\"OSFamily\" value:\"linux\"\n")
		b.WriteString("}\n")
		b.WriteString("\n")
	}

	// CI combined config
	if g.CacheEnabled || g.ExecutorEnabled {
		b.WriteString("# CI config combines remote cache and executor.\n")
		b.WriteString("build:ci --config=remote-cache\n")
		if g.ExecutorEnabled {
			b.WriteString("build:ci --config=remote-exec\n")
		}
		b.WriteString("build:ci --verbose_failures\n")
		b.WriteString("build:ci --keep_going\n")
		b.WriteString("\n")
	}

	// Default platform
	b.WriteString("# Default: use host platform.\n")
	b.WriteString("build --platforms=@local_config_platform//:host\n")
	b.WriteString("\n")

	return b.String()
}

func (g *Generator) generateModuleBazel(repos []ManifestRepository) string {
	var b strings.Builder
	b.WriteString("# Generated by monofs-bazelctl -- DO NOT EDIT\n")
	b.WriteString("# Regenerate: monofs-bazelctl sync\n")
	b.WriteString(fmt.Sprintf("# Generated at: %s\n", time.Now().UTC().Format(time.RFC3339)))
	b.WriteString("\n")
	b.WriteString(`module(
    name = "monofs_workspace",
    version = "0.0.0",
)
`)
	b.WriteString("\n")

	// Sort repos for deterministic output
	sorted := make([]ManifestRepository, len(repos))
	copy(sorted, repos)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].DisplayPath < sorted[j].DisplayPath
	})

	if len(sorted) > 0 {
		b.WriteString("# ── Ingested repositories ──\n")
		b.WriteString("# Each repo is a local_path_override so Bazel treats it as\n")
		b.WriteString("# a module living inside the virtual monorepo.\n")
		b.WriteString("\n")
		for _, repo := range sorted {
			modName := DisplayPathToModuleName(repo.DisplayPath)
			b.WriteString(fmt.Sprintf("bazel_dep(name = %q, version = \"0.0.0\")\n", modName))
			b.WriteString(fmt.Sprintf("local_path_override(\n"))
			b.WriteString(fmt.Sprintf("    module_name = %q,\n", modName))
			b.WriteString(fmt.Sprintf("    path = %q,\n", repo.DisplayPath))
			b.WriteString(")\n")
			b.WriteString("\n")
		}
	}

	return b.String()
}

func (g *Generator) generateWorkspace(repos []ManifestRepository) string {
	var b strings.Builder
	b.WriteString("# Generated by monofs-bazelctl -- DO NOT EDIT\n")
	b.WriteString("# Legacy WORKSPACE for rules not yet on Bzlmod.\n")
	b.WriteString("# Prefer MODULE.bazel for new dependencies.\n")
	b.WriteString(fmt.Sprintf("# Generated at: %s\n", time.Now().UTC().Format(time.RFC3339)))
	b.WriteString("\n")
	b.WriteString(`workspace(name = "monofs_workspace")
`)
	b.WriteString("\n")

	if len(repos) == 0 {
		return b.String()
	}

	sorted := make([]ManifestRepository, len(repos))
	copy(sorted, repos)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].DisplayPath < sorted[j].DisplayPath
	})

	b.WriteString("# Ingested repos as local_repository.\n")
	for _, repo := range sorted {
		modName := DisplayPathToModuleName(repo.DisplayPath)
		b.WriteString(fmt.Sprintf(
			`local_repository(
    name = %q,
    path = %q,
)
`, modName, repo.DisplayPath))
		b.WriteString("\n")
	}

	return b.String()
}

func (g *Generator) generateRootBuild(repos []ManifestRepository) string {
	var b strings.Builder
	b.WriteString(`# Generated by monofs-bazelctl -- DO NOT EDIT
# Root BUILD -- empty, all targets are in subdirectories.
# This file exists so that Bazel treats the mount root as a valid workspace.
`)
	// Generate a filegroup for each top-level display_path component
	// so that "bazel build //..." traverses into repos.
	_ = repos // reserved for future use (filegroup per top-level dir)
	return b.String()
}
