// Package buildcache defines the interface for generating build-system-specific
// cache artifacts. Each build system (Go, npm, Cargo, Bazel) implements
// ArtifactGenerator to produce metadata entries that describe cache files
// needed for offline builds.
//
// IMPORTANT: Generators produce METADATA ONLY. No file content is generated
// at ingestion time. Content is generated on-demand by fetchers when FUSE reads occur.
package buildcache

// ArtifactType identifies the kind of cache artifact to generate.
type ArtifactType string

const (
	// Go module download cache artifacts (under $GOMODCACHE/cache/download/)
	ArtifactGoModInfo    ArtifactType = "go_mod_info"    // .info JSON metadata
	ArtifactGoModFile    ArtifactType = "go_mod_file"    // .mod file (go.mod content)
	ArtifactGoModZip     ArtifactType = "go_mod_zip"     // .zip source archive
	ArtifactGoModZipHash ArtifactType = "go_mod_ziphash" // .ziphash (h1:... checksum)
	ArtifactGoModList    ArtifactType = "go_mod_list"    // list file (version list)
	ArtifactGoModLock    ArtifactType = "go_mod_lock"    // .lock (empty download sentinel)
)

// ArtifactEntry is a metadata-only description of a cache file that should
// exist in the virtual filesystem. No content is stored — fetchers generate
// content on read.
//
// These entries are converted to VirtualEntry items by layout mappers,
// then stored as FileMetadata on server nodes. When FUSE reads the file,
// the server passes BackendMetadata (including artifact_type) to the fetcher,
// which generates the actual bytes.
type ArtifactEntry struct {
	// RelativePath within the virtual layout, under the cache prefix.
	// Example: "cache/download/github.com/google/uuid/@v/v1.6.0.info"
	RelativePath string

	// Type identifies what the fetcher should generate when this file is read.
	Type ArtifactType

	// Size is the expected content size in bytes.
	// Set to the exact value when computable at ingestion time (list, lock, mod),
	// or 0 when the size depends on on-demand fetcher generation (info, zip, ziphash).
	Size uint64

	// Metadata is propagated into FileMetadata.BackendMetadata on server nodes.
	// Must contain enough information for the fetcher to generate content.
	// Standard keys: "artifact_type", "module", "version", "generatable"
	Metadata map[string]string
}

// ArtifactGenerator produces metadata entries for build-cache files.
// Each build system (Go, npm, Cargo) implements this interface once.
//
// Generators run at INGESTION TIME on the ROUTER — they produce METADATA ONLY.
// The actual file content is generated by fetchers on-demand during reads.
type ArtifactGenerator interface {
	// BuildSystem returns the identifier: "go", "npm", "cargo", "bazel".
	BuildSystem() string

	// ShouldGenerate returns true if this generator applies to the ingestion type.
	ShouldGenerate(ingestionType string) bool

	// GenerateEntries returns metadata entries for all cache artifacts
	// that should exist alongside the primary source files.
	// params contains module/package identity extracted during ingestion.
	GenerateEntries(params ArtifactParams) ([]ArtifactEntry, error)
}

// ArtifactParams holds identity information extracted during ingestion.
// Each field is used by the corresponding generator; unused fields can be empty.
type ArtifactParams struct {
	// ModulePath is the Go module path (e.g., "github.com/google/uuid").
	// Used by: Go generator.
	ModulePath string

	// Version is the version string (e.g., "v1.6.0").
	// Used by: Go generator, npm generator, Cargo generator.
	Version string

	// Source is the original source URL passed to ingest.
	Source string

	// GoModFileSize is the size of go.mod from the ingested source files.
	// Used by the Go generator to set the correct Size for the .mod artifact.
	// 0 means unknown.
	GoModFileSize uint64

	// Extra holds backend-specific fields for future backends.
	//   npm: "package_name", "registry_url"
	//   cargo: "crate_name", "index_url"
	Extra map[string]string
}
